# golangci-lint configuration for s9s
version: "2"

run:
  timeout: 10m
  tests: true
  skip-dirs:
    - vendor
    - .git
    - .github

linters:
  disable-all: true
  enable:
    # Core linters - focusing on critical issues only
    - errcheck      # Unchecked errors are critical
    - govet         # Suspicious constructs
    - ineffassign   # Ineffective assignments

  disable:
    # Explicitly disable these linters - they will be fixed in follow-up PRs
    - staticcheck   # 83 issues remaining
    - gosec         # 147 issues remaining
    - unused        # 1 issue remaining

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Allow _ = assignment for intentionally ignored errors

  govet:
    enable:
      - shadow

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

  exclude-dirs:
    - vendor
    - third_party
    - testdata

  exclude-rules:
    # Exclude shadow warnings for common err pattern
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

  max-issues-per-linter: 0
  max-same-issues: 0
