run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - .git
    - .github

linters:
  enable:
    - gofmt
    - goimports
    - golint
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gosec
    - megacheck
    - dupl
    - misspell
    - lll
    - nakedret
    - prealloc
    - exportloopref
    - gocritic
    - gochecknoinits
    - gocyclo
    - gocognit
    - godox
    - maligned
    - nestif
    - gomodguard
    - asciicheck

  disable:
    - depguard
    - gochecknoglobals

linters-settings:
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/jontk/s9s
  
  golint:
    min-confidence: 0.8
  
  govet:
    check-shadowing: true
  
  misspell:
    locale: US
  
  lll:
    line-length: 120
    tab-width: 4
  
  nakedret:
    max-func-lines: 30
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  
  gocyclo:
    min-complexity: 15
  
  gocognit:
    min-complexity: 20
  
  godox:
    keywords:
      - TODO
      - FIXME
      - HACK
  
  gomodguard:
    allowed:
      modules:
        - github.com/gdamore/tcell/v2
        - github.com/rivo/tview
        - github.com/spf13/viper
        - github.com/rs/zerolog
        - github.com/stretchr/testify
      domains:
        - github.com

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gocritic
    
    - linters:
        - lll
      source: "^//go:generate "
    
    - linters:
        - staticcheck
      text: "SA9003:"
    
    - linters:
        - golint
      text: "should have comment or be unexported"

  max-issues-per-linter: 50
  max-same-issues: 10
  new: false