# golangci-lint configuration for s9s
version: "2"

run:
  timeout: 10m
  tests: true
  skip-dirs:
    - vendor
    - .git
    - .github

linters:
  disable-all: true
  enable:
    # Core linters - focusing on critical issues only
    - errcheck      # Unchecked errors are critical
    - govet         # Suspicious constructs
    - ineffassign   # Ineffective assignments
    # staticcheck: 82/82 Phase 1 issues fixed (PR #13 + PR #16) ✅
    - staticcheck   # Enabled: all Phase 1 issues resolved

    # Additional linters - Phase 7
    # Note: gofumpt and goimports are handled by pre-commit hooks and Makefile
    - misspell      # Check for commonly misspelled English words
    - bodyclose     # Check HTTP response body is closed
    - errorlint     # Find code that will cause problems with Go 1.13 error wrapping (fixed in this PR)
    - wastedassign  # Finds wasted assignment statements (fixed in this PR)

  disable:
    # Temporarily disabled - will be fixed in follow-up PRs
    - unused        # 1 issue
    # gosec: Phase 2 progress - 15/40 file permission issues fixed
    # Remaining 24 issues: G304 (8), G115 (10), G602 (5), G101 (1)
    - gosec
    - gocritic      # 51 pre-existing style issues (ifElseChain, singleCaseSwitch, dupBranchBody)
    - noctx         # 23 pre-existing issues in test HTTP requests
    - prealloc      # 16 pre-existing performance micro-optimizations
    - unconvert     # 8 pre-existing unnecessary type conversions
    - unparam       # 38 pre-existing unused parameters

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Allow _ = assignment for intentionally ignored errors

  govet:
    enable:
      - shadow

  gosec:
    # Security severity threshold
    severity: medium
    confidence: medium
    # Exclude specific rules that are false positives or acceptable in our context
    excludes:
      # G204 is often a false positive when using exec.Command with separate args
      # We've reviewed all exec.Command usage and they use proper argument separation
      - G204

  gocritic:
    # Enable multiple checks by tags
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain  # Style preference, too many pre-existing instances
      - singleCaseSwitch  # Style preference, too many pre-existing instances
      - dupBranchBody  # Acceptable in some cases
      - octalLiteral
      - whyNoLint

  errorlint:
    # Check whether fmt.Errorf uses the %w verb for formatting errors
    errorf: true
    # Check for plain type assertions and type switches
    asserts: true
    # Check for plain error comparisons
    comparison: true

  misspell:
    # Correct spellings using locale preferences for US or UK
    locale: US

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

  exclude-dirs:
    - vendor
    - third_party
    - testdata

  exclude-rules:
    # Exclude shadow warnings for common err pattern
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

    # G304: File inclusion via variable is acceptable for application-controlled paths
    # These files manage application configuration and persistent data (not user-supplied)
    - text: "G304:"
      linters:
        - gosec
      path: "plugins/observability/(cmd/plugin/export|historical|security/secrets|subscription/persistence)"

    # G304 in tests (test data files are application-controlled)
    - text: "G304:"
      linters:
        - gosec
      path: "test/(integration/ssh_integration|performance|security.*_test)\\.go"

    # Test files: G115 (integer overflow), G602 (slice index), G101 (hardcoded credentials)
    # These are acceptable in test code (type conversions, test keys, modulo operations)
    - text: "(G115|G602|G101):"
      linters:
        - gosec
      path: "_test\\.go"

    # G301/G306: Allow standard file permissions in test and setup contexts
    - text: "(G301|G306):"
      linters:
        - gosec
      path: "test/"

    # unparam: Unused parameters in tests are acceptable
    - text: "- .* is unused"
      linters:
        - unparam
      path: "_test\\.go"

    # unparam: Functions that always return nil are acceptable if designed for future errors
    # These functions are intentionally designed to return errors for extensibility
    - text: "result 0 \\(error\\) is always nil"
      linters:
        - unparam
      path: "internal/app/app\\.go"

    # Exclude certain linters from test files - tests have different patterns
    - linters:
        - unparam
        - prealloc
        - gocritic
        - gosec  # G115, G602, G101 acceptable in tests
      path: "_test\\.go"

    # noctx: Test HTTP requests don't need context
    - linters:
        - noctx
      path: "(test|_test)\\.go"

    # Pre-existing gosec issues in auth and config packages
    - text: "G404: Use of weak random"
      linters:
        - gosec
      path: "internal/auth/"

    - text: "(G301|G304|G306):"
      linters:
        - gosec
      path: "(internal/auth|internal/config|internal/cli)/"

    # G115: Integer overflow conversions in observability plugins are acceptable
    # (NumGoroutine fits in int32, memory metrics conversions are safe)
    - text: "G115:"
      linters:
        - gosec
      path: "(metrics|prometheus)"

    # Pre-existing unconvert issues
    - linters:
        - unconvert

    # Pre-existing unparam issues (except in files we specifically modified)
    - linters:
        - unparam
      path: "internal/(views|ui|layouts|discovery|monitoring|ssh)/"

    # Pre-existing prealloc suggestions
    - linters:
        - prealloc

  max-issues-per-linter: 0
  max-same-issues: 0
