#!/usr/bin/env bash
# Set up s9s config for all local k3s Slurm clusters
#
# Generates JWT tokens, resolves ClusterIPs, optionally seeds clusters with
# test data, and writes a multi-cluster s9s config file.
#
# Usage:
#   ./scripts/dev-clusters.sh              # Generate config + seed all clusters
#   ./scripts/dev-clusters.sh --no-seed    # Generate config only (skip seeding)
#   ./scripts/dev-clusters.sh --seed-only  # Seed only (assumes config exists)
#
# After running, start s9s with:
#   s9s --config /tmp/s9s-dev/config.yaml --no-discovery
#   s9s --config /tmp/s9s-dev/config.yaml --cluster slurm-2511 --no-discovery

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SEED_SCRIPT="$PROJECT_ROOT/test/vhs-integration/scripts/seed-cluster.sh"
GET_TOKEN="$PROJECT_ROOT/test/vhs-integration/scripts/get-token.sh"

CONFIG_DIR="/tmp/s9s-dev"
CONFIG_FILE="$CONFIG_DIR/config.yaml"

# Cluster definitions: namespace -> highest supported API version
declare -A CLUSTER_API_VERSION=(
    [slurm-2405]="v0.0.41"
    [slurm-2411]="v0.0.42"
    [slurm-2505]="v0.0.43"
    [slurm-2511]="v0.0.44"
)

ALL_NAMESPACES=("slurm-2405" "slurm-2411" "slurm-2505" "slurm-2511")

# Parse arguments
SEED=true
SEED_ONLY=false
while [[ $# -gt 0 ]]; do
    case "$1" in
        --no-seed)
            SEED=false
            shift
            ;;
        --seed-only)
            SEED_ONLY=true
            shift
            ;;
        -h|--help)
            sed -n '2,/^$/s/^# //p' "$0"
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC} $*"; }
ok()    { echo -e "${GREEN}[OK]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
fail()  { echo -e "${RED}[FAIL]${NC} $*"; }

# Seed only mode
if $SEED_ONLY; then
    if [[ ! -f "$SEED_SCRIPT" ]]; then
        fail "Seed script not found: $SEED_SCRIPT"
        exit 1
    fi
    for ns in "${ALL_NAMESPACES[@]}"; do
        info "Seeding $ns..."
        "$SEED_SCRIPT" "$ns" || warn "Seeding failed for $ns"
    done
    ok "All clusters seeded"
    exit 0
fi

# Check required tools
for tool in kubectl curl; do
    if ! command -v "$tool" &>/dev/null; then
        fail "Required tool not found: $tool"
        exit 1
    fi
done

mkdir -p "$CONFIG_DIR"

# Discover clusters and generate tokens
declare -A CLUSTER_IPS
declare -A CLUSTER_TOKENS
AVAILABLE_NAMESPACES=()

info "Discovering clusters..."
for ns in "${ALL_NAMESPACES[@]}"; do
    # Resolve ClusterIP
    ip=$(kubectl get svc slurmrestd -n "$ns" -o jsonpath='{.spec.clusterIP}' 2>/dev/null) || true
    if [[ -z "$ip" ]]; then
        warn "$ns: slurmrestd service not found — skipping"
        continue
    fi

    # Generate JWT token
    token=$("$GET_TOKEN" "$ns" 2>/dev/null) || true
    if [[ -z "$token" ]]; then
        warn "$ns: failed to generate JWT token — skipping"
        continue
    fi

    # Verify connectivity
    api_ver="${CLUSTER_API_VERSION[$ns]}"
    http_code=$(curl -s -o /dev/null -w "%{http_code}" \
        -H "X-SLURM-USER-NAME: root" \
        -H "X-SLURM-USER-TOKEN: $token" \
        "http://${ip}:6820/slurm/${api_ver}/ping" 2>/dev/null) || true
    if [[ "$http_code" != "200" ]]; then
        warn "$ns: connectivity check failed (HTTP $http_code) — skipping"
        continue
    fi

    CLUSTER_IPS[$ns]="$ip"
    CLUSTER_TOKENS[$ns]="$token"
    AVAILABLE_NAMESPACES+=("$ns")
    ok "$ns: connected at $ip (API $api_ver)"
done

if [[ ${#AVAILABLE_NAMESPACES[@]} -eq 0 ]]; then
    fail "No clusters available"
    exit 1
fi

# Seed clusters
if $SEED; then
    if [[ -f "$SEED_SCRIPT" ]]; then
        echo ""
        for ns in "${AVAILABLE_NAMESPACES[@]}"; do
            info "Seeding $ns with test data..."
            "$SEED_SCRIPT" "$ns" || warn "Seeding failed for $ns"
        done
        sleep 2  # Let Slurm schedule the jobs
    else
        warn "Seed script not found: $SEED_SCRIPT — skipping"
    fi
fi

# Build config file
info "Writing config to $CONFIG_FILE..."

DEFAULT_CLUSTER="${AVAILABLE_NAMESPACES[0]}"

cat > "$CONFIG_FILE" <<EOF
# s9s development config — generated by dev-clusters.sh
# $(date -u +"%Y-%m-%dT%H:%M:%SZ")
#
# Switch clusters by changing defaultCluster below, or use the
# settings UI inside s9s (view 6).

defaultCluster: $DEFAULT_CLUSTER

clusters:
EOF

for ns in "${AVAILABLE_NAMESPACES[@]}"; do
    ip="${CLUSTER_IPS[$ns]}"
    token="${CLUSTER_TOKENS[$ns]}"
    api_ver="${CLUSTER_API_VERSION[$ns]}"

    cat >> "$CONFIG_FILE" <<EOF
  - name: $ns
    cluster:
      endpoint: http://${ip}:6820
      token: "$token"
      apiVersion: $api_ver
      insecure: true
      timeout: 30s

EOF
done

cat >> "$CONFIG_FILE" <<EOF
refreshRate: 2s
maxRetries: 3

discovery:
  enabled: false
EOF

echo ""
echo -e "${BOLD}=== Dev Clusters Config Ready ===${NC}"
echo ""
echo -e "  Config: ${GREEN}$CONFIG_FILE${NC}"
echo -e "  Clusters: ${AVAILABLE_NAMESPACES[*]}"
echo -e "  Default:  ${BOLD}$DEFAULT_CLUSTER${NC}"
echo ""
echo -e "  ${BOLD}Usage:${NC}"
echo -e "    s9s --config $CONFIG_FILE --no-discovery"
echo ""
echo -e "  ${BOLD}Switch cluster:${NC}"
echo -e "    s9s --config $CONFIG_FILE --cluster slurm-2511 --no-discovery"
echo -e "    or edit defaultCluster in $CONFIG_FILE"
echo ""
echo -e "  ${BOLD}Re-seed clusters:${NC}"
echo -e "    $0 --seed-only"
echo ""
echo -e "  ${YELLOW}Note: JWT tokens expire in 1 hour. Re-run this script to refresh.${NC}"
